### ISSUE TITLE
All menu items 404 after install CE 1.9.3.7

### ISSUE THREAD

**Issue by shoetrees** [GetResponse/magento#10]
All menu items 404 after install CE 1.9.3.7, so unable to link to Getresponse site and get API credentials. Nothing in error logs.

**Comment by rkarkut** [comment]
Unfortunately, I cannot replicate your problem. I have installed Magento 1.9.3.7 (version magento-1.9.3.7-2017-11-27-05-29-14) and our latest package (version GetResponse-19.1.12). 
During my test I didn't notice any anomaly. Also we didn't get similar reports until now.

**Comment by shoetrees** [comment]
I upgraded to the latest from github. Same thing.

See attached.

Can you tell me are the URLs when I click menu item correct – they look very strange ??

 

Thanks

Jake
