### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by darekkosyl** [GetResponse/magento#13]
Hi there, I am trying to install GetResponse integration on our magento 2.2.5
dev site . I followed your guide from github:

> Copy GetResponseIntegration folder to
> magento_main_folder/app/code/GetResponse/
> 
> To install plugin run in console commands:
> 
> php bin/magento module:enable GetResponse_GetResponseIntegration
> 
> php bin/magento setup:upgrade

I get the error as below at the last step :

> Installing schema... SQLSTATE[23000]: Integrity constraint violation: 1062
> Duplicate entry '1' for key 'PRIMARY', query was: INSERT INTO
> `getresponse_customs` (`id`, `id_shop`, `custom_field`, `custom_value`,
> `custom_name`, `default`, `active_custom`) VALUES (?, ?, ?, ?, ?, ?, ?)
> 

Can you help with that?

Thanks ,

Darek

**Comment by rkarkut** [comment]
Hello, could you try our latest version? It should works properly right now.
