### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by drag0nman** [GetResponse/magento#36]
Hello,
I have installed without problem the module.
But in magento backend I can't do any action.
For example when I try to export the User I got this error:

2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yoffice.customer_entity' doesn't exist, query was: SELECT `main_table`.*, `customer_entity`.*, `customer_address_entity`.* FROM `mag_newsletter_subscriber` AS `main_table`
LEFT JOIN `customer_entity` ON customer_entity.entity_id=main_table.customer_id
LEFT JOIN `customer_address_entity` ON customer_address_entity.entity_id=default_billing WHERE (subscriber_status=1)
Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yoffice.customer_entity' doesn't exist

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yoffice.customer_entity' doesn't exist, query was: SELECT `main_table`.*, `customer_entity`.*, `customer_address_entity`.* FROM `mag_newsletter_subscriber` AS `main_table`
LEFT JOIN `customer_entity` ON customer_entity.entity_id=main_table.customer_id
LEFT JOIN `customer_address_entity` ON customer_address_entity.entity_id=default_billing WHERE (subscriber_status=1)
Message Input

any suggestions?
Thank you

**Comment by BartStep** [comment]
Hi, 
- Please check if table "customer_entity" exists in your magento database. 
- When user register to store, then new records should appear in this table. (please confirm this it works, and only our module has problem with accessing customer data)

**Comment by drag0nman** [comment]
Hello,
no the table "customer_entity" doesn't exist.
In database there is a table mag_customer_entity, In this installation there are the prefix "mag_"

**Comment by BartStep** [comment]
Ok, that is the bug. We will try to fix it.

**Comment by drag0nman** [comment]
Ok!
Do you know how long it take to fix it?

**Comment by drag0nman** [comment]
Any news?

**Comment by BartStep** [comment]
I'll try to solve it this week.

**Comment by drag0nman** [comment]
Ok, tnx I'm waiting for you

**Comment by BartStep** [comment]
@drag0nman Issue should be fixed with tag: 20.3.9
