### ISSUE TITLE
The newsletter registration form does not work!

### ISSUE THREAD

**Issue by tiziano-seguida** [GetResponse/magento#40]
Hi,
I installed the latest version of the module via composer. 
I followed this procedure [link](https://www.getresponse.com/help/ecommerce/magento-and-getresponse/can-i-grow-contact-database-by-integrating-getresponse-with-magento.html) in order to configure the module. 

I am now experiencing a weird behaviour for this module, since I do get this error message 

> Something went wrong with the subscription

even though I do receive the `GetResponse list` invitation email correctly.

Any suggestions?
Thank you

Magento Version: 2.2.3
GetResponse: 20.3.9

**Comment by drag0nman** [comment]
I have also this problem.
This is a log by system.log


main.CRITICAL: Exception message: Email in GrShareCode\Contact\Command\AddContactCommand cannot be a blank string
Trace: #0 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Newsletter\Model\Subscriber->subscribe('pasfiahsuhasiba...')
#1 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Newsletter\Model\Subscriber\Interceptor->___callParent('subscribe', Array)
#2 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Newsletter\Model\Subscriber\Interceptor->Magento\Framework\Interception\{closure}('pasfiahsuhasiba...')
#3 /var/www/html/yoffice/generated/code/Magento/Newsletter/Model/Subscriber/Interceptor.php(26): Magento\Newsletter\Model\Subscriber\Interceptor->___callPlugins('subscribe', Array, Array)
#4 /var/www/html/yoffice/vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php(136): Magento\Newsletter\Model\Subscriber\Interceptor->subscribe('pasfiahsuhasiba...')
#5 /var/www/html/yoffice/vendor/magento/framework/App/Action/Action.php(107): Magento\Newsletter\Controller\Subscriber\NewAction->execute()
#6 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('dispatch', Array)
#8 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /var/www/html/yoffice/generated/code/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php(26): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callPlugins('dispatch', Array, Array)
#10 /var/www/html/yoffice/vendor/magento/framework/App/FrontController.php(55): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#13 /var/www/html/yoffice/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /var/www/html/yoffice/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/yoffice/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/yoffice/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#19 /var/www/html/yoffice/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/yoffice/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#21 /var/www/html/yoffice/index.php(41): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#22 {main} [] []

**Comment by drag0nman** [comment]
Any news?

**Comment by BartStep** [comment]
Issue was fixed and it's available with tag 20.3.10.

**Comment by mannanmughal** [comment]
Hello Guys, I'm using Magento 2.3.3p1
My issue is quite similar, can anyone help?

This is the system error log;

1 exception(s):
Exception #0 (GrShareCode\Validation\Assert\InvalidArgumentException): Email in GrShareCode\Contact\Command\AddContactCommand cannot be a blank string

Exception #0 (GrShareCode\Validation\Assert\InvalidArgumentException): Email in GrShareCode\Contact\Command\AddContactCommand cannot be a blank string
<pre>#1 GrShareCode\Validation\Assert\Assertion::notNull(NULL, 'Email in GrShare...', NULL) called at [vendor/getresponse/share-code-plugin/src/Validation/Assert/AssertionChain.php:180]
#2 GrShareCode\Validation\Assert\AssertionChain->__call('notNull', array(NULL, 'Email in GrShare...', NULL)) called at [vendor/getresponse/share-code-plugin/src/Contact/Command/AddContactCommand.php:42]
#3 GrShareCode\Contact\Command\AddContactCommand->__construct(NULL, '', 'x', NULL, &GrShareCode\Contact\ContactCustomField\ContactCustomFieldsCollection#000000005e5b4e7c000000002a1db586#) called at [vendor/getresponse/share-code-plugin/src/Export/ExportContactService.php:55]
#4 GrShareCode\Export\ExportContactService->exportCustomer(&GrShareCode\Export\Command\ExportContactCommand#000000005e5b4e75000000002a1db586#) called at [vendor/getresponse/share-code-plugin/src/Export/ExportContactService.php:40]
#5 GrShareCode\Export\ExportContactService->exportContact(&GrShareCode\Export\Command\ExportContactCommand#000000005e5b4e75000000002a1db586#) called at [vendor/getresponse/magento2/Domain/GetResponse/ExportOnDemand/ExportOnDemandService.php:44]
#6 GetResponse\GetResponseIntegration\Domain\GetResponse\ExportOnDemand\ExportOnDemandService->export(&Magento\Newsletter\Model\Subscriber#000000005e5b23a3000000002a1db586#, &GetResponse\GetResponseIntegration\Domain\GetResponse\ExportOnDemand\ExportOnDemand#000000005e5b23a6000000002a1db586#) called at [vendor/getresponse/magento2/Controller/Adminhtml/Export/Process.php:95]
#7 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process->execute() called at [generated/code/GetResponse/GetResponseIntegration/Controller/Adminhtml/Export/Process/Interceptor.php:24]
#8 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#9 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#10 Magento\Backend\App\AbstractAction->dispatch(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#13 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#14 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#15 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#16 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#17 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#18 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#19 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#20 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#21 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#22 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#23 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#24 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#25 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#26 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#27 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#28 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#29 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#30 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#31 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#32 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#33 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#34 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#35 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#36 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#37 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#38 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#39 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#40 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#41 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#42 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#43 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#44 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#45 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#46 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#47 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#48 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#49 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#50 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#51 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#52 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#53 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#54 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#55 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#56 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#57 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#58 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#59 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#60 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#61 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#62 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#63 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#64 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#65 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#66 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#67 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#68 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#69 WeltPixel\Backend\Plugin\Utility->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#70 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#71 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(&GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#, &Closure#000000005e5b0ad4000000002a1db586#, &Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#72 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#73 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#), NULL) called at [generated/code/GetResponse/GetResponseIntegration/Controller/Adminhtml/Export/Process/Interceptor.php:39]
#74 GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/App/FrontController.php:159]
#75 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#, &GetResponse\GetResponseIntegration\Controller\Adminhtml\Export\Process\Interceptor#000000005e5b0ad2000000002a1db586#) called at [vendor/magento/framework/App/FrontController.php:99]
#76 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#77 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#78 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#79 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#), array(array('default_store_se...', 'page_cache_from_...', 'storeCookieValid...', 'install', 'configHash'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#80 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000005e5b0ed9000000002a1db586#) called at [vendor/magento/framework/App/Http.php:137]
#81 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#82 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#83 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000005e5b0eaa000000002a1db586#) called at [index.php:39]
</pre>
