### ISSUE TITLE
problem with checkout page

### ISSUE THREAD

**Issue by francolanza** [GetResponse/magento#5]
hello, I use checkout module from advance checkout module ( http://www.advancedcheckout.com/ ) , in installing getresponse magento module there is an issue to using module, when I insert a customer name , I see this error code ( SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kg21mu4h surveystore.getresponse shops' doesn't exist, query was: SELECT `getresponse_shops`.* FROM `getresponse_shops` WHERE (`getresponse_shops`.`shop_id`='1') . could you help me to resolve this issue?

many thanks
best regards
franco

**Comment by rkarkut** [comment]
Hello,
Thank you for contacting us.

One of required tables don't exists in your database. Could you re-install our module? It it will not solve your problem please contact our DevZone:
https://app.getresponse.com/feedback.html?devzone=yes

We will try to help you resolve this problem.
