### ISSUE TITLE
Error on reorder from Admin Panel

### ISSUE THREAD

**Issue by br33f** [GetResponse/magento#57]
**Magento 2.4.2**
**Module version 20.5.7**

When trying to Reorder - after order submit (uri: **admin/sales/order_create/save**)

I get following Error:
`TypeError: Argument 3 passed to GetResponse\GetResponseIntegration\Api\Customer::__construct() must be of the type string, null given, called in /storage/home/www/magento-test/vendor/getresponse/magento2/Api/CustomerFactory.php on line 115 and defined in /storage/home/www/magento-test/vendor/getresponse/magento2/Api/Customer.php:20 Stack trace: #0 /storage/home/www/magento-test/vendor/getresponse/magento2/Api/CustomerFactory.php(115): GetResponse\GetResponseIntegration\Api\Customer->__construct() #1 /storage/home/www/magento-test/vendor/getresponse/magento2/Api/OrderFactory.php(38): GetResponse\GetResponseIntegration\Api\CustomerFactory->createFromOrder() #2 /storage/home/www/magento-test/vendor/getresponse/magento2/Api/ApiService.php(155): GetResponse\GetResponseIntegration\Api\OrderFactory->create() #3 /storage/home/www/magento-test/vendor/getresponse/magento2/Observer/Admin/OrderObserver.php(71): GetResponse\GetResponseIntegration\Api\ApiService->updateOrder() #4 /storage/home/www/magento-test/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): GetResponse\GetResponseIntegration\Observer\Admin\OrderObserver->execute() #5 /storage/home/www/magento-test/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() #6 /storage/home/www/magento-test/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch() #7 /storage/home/www/magento-test/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch() #8 /storage/home/www/magento-test/vendor/magento/framework/Model/AbstractModel.php(829): Magento\Framework\Event\Manager\Proxy->dispatch() #9 /storage/home/www/magento-test/vendor/magento/framework/Model/ResourceModel/Db/VersionControl/AbstractDb.php(56): Magento\Framework\Model\AbstractModel->afterSave() #10 /storage/home/www/magento-test/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(424): Magento\Framework\Model\ResourceModel\Db\VersionControl\AbstractDb->processAfterSaves() #11 /storage/home/www/magento-test/vendor/magento/module-sales/Model/ResourceModel/Order.php(180): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save() #12 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\ResourceModel\Order->save() #13 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\ResourceModel\Order\Interceptor->___callParent() #14 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\ResourceModel\Order\Interceptor->Magento\Framework\Interception\{closure}() #15 /storage/home/www/magento-test/generated/code/Magento/Sales/Model/ResourceModel/Order/Interceptor.php(32): Magento\Sales\Model\ResourceModel\Order\Interceptor->___callPlugins() #16 /storage/home/www/magento-test/vendor/magento/module-sales/Model/OrderRepository.php(276): Magento\Sales\Model\ResourceModel\Order\Interceptor->save() #17 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\OrderRepository->save() #18 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\OrderRepository\Interceptor->___callParent() #19 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}() #20 /storage/home/www/magento-test/generated/code/Magento/Sales/Model/OrderRepository/Interceptor.php(59): Magento\Sales\Model\OrderRepository\Interceptor->___callPlugins() #21 /storage/home/www/magento-test/vendor/magento/module-sales/Model/Service/OrderService.php(216): Magento\Sales\Model\OrderRepository\Interceptor->save() #22 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place() #23 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent() #24 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}() #25 /storage/home/www/magento-test/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(32): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins() #26 /storage/home/www/magento-test/vendor/magento/module-quote/Model/QuoteManagement.php(566): Magento\Sales\Model\Service\OrderService\Interceptor->place() #27 /storage/home/www/magento-test/vendor/magento/module-quote/Model/QuoteManagement.php(456): Magento\Quote\Model\QuoteManagement->submitQuote() #28 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit() #29 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent() #30 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}() #31 /storage/home/www/magento-test/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(23): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins() #32 /storage/home/www/magento-test/vendor/magento/module-sales/Model/AdminOrder/Create.php(1978): Magento\Quote\Model\QuoteManagement\Interceptor->submit() #33 /storage/home/www/magento-test/vendor/magento/module-sales/Controller/Adminhtml/Order/Create/Save.php(52): Magento\Sales\Model\AdminOrder\Create->createOrder() #34 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Create\Save->execute() #35 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callParent() #36 /storage/home/www/magento-test/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->Magento\Framework\Interception\{closure}() #37 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() #38 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->Magento\Framework\Interception\{closure}() #39 /storage/home/www/magento-test/generated/code/Magento/Sales/Controller/Adminhtml/Order/Create/Save/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callPlugins() #40 /storage/home/www/magento-test/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->execute() #41 /storage/home/www/magento-test/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch() #42 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch() #43 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callParent() #44 /storage/home/www/magento-test/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->Magento\Framework\Interception\{closure}() #45 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() #46 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->Magento\Framework\Interception\{closure}() #47 /storage/home/www/magento-test/generated/code/Magento/Sales/Controller/Adminhtml/Order/Create/Save/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callPlugins() #48 /storage/home/www/magento-test/vendor/magento/framework/App/FrontController.php(186): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->dispatch() #49 /storage/home/www/magento-test/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest() #50 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch() #51 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent() #52 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() #53 /storage/home/www/magento-test/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins() #54 /storage/home/www/magento-test/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch() #55 /storage/home/www/magento-test/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch() #56 /storage/home/www/magento-test/pub/index.php(29): Magento\Framework\App\Bootstrap->run() #57 {main}`

Order details:
- customer NOT LOGGED IN
- Shipping address provided
- Billing address same as billing

Please let me know if you need more data.

**Comment by Eyekandy** [comment]
> **Magento 2.4.2** **Module version 20.5.7**
> 
> When trying to Reorder - after order submit (uri: **admin/sales/order_create/save**)
> 
> I get following Error: `TypeError: Argument 3 passed to GetResponse\GetResponseIntegration\Api\Customer::__construct() must be of the type string, null given, called in /storage/home/www/magento-test/vendor/getresponse/magento2/Api/CustomerFactory.php on line 115 and defined in /storage/home/www/magento-test/vendor/getresponse/magento2/Api/Customer.php:20 Stack trace: #0 /storage/home/www/magento-test/vendor/getresponse/magento2/Api/CustomerFactory.php(115): GetResponse\GetResponseIntegration\Api\Customer->__construct() #1 /storage/home/www/magento-test/vendor/getresponse/magento2/Api/OrderFactory.php(38): GetResponse\GetResponseIntegration\Api\CustomerFactory->createFromOrder() #2 /storage/home/www/magento-test/vendor/getresponse/magento2/Api/ApiService.php(155): GetResponse\GetResponseIntegration\Api\OrderFactory->create() #3 /storage/home/www/magento-test/vendor/getresponse/magento2/Observer/Admin/OrderObserver.php(71): GetResponse\GetResponseIntegration\Api\ApiService->updateOrder() #4 /storage/home/www/magento-test/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): GetResponse\GetResponseIntegration\Observer\Admin\OrderObserver->execute() #5 /storage/home/www/magento-test/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() #6 /storage/home/www/magento-test/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch() #7 /storage/home/www/magento-test/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch() #8 /storage/home/www/magento-test/vendor/magento/framework/Model/AbstractModel.php(829): Magento\Framework\Event\Manager\Proxy->dispatch() #9 /storage/home/www/magento-test/vendor/magento/framework/Model/ResourceModel/Db/VersionControl/AbstractDb.php(56): Magento\Framework\Model\AbstractModel->afterSave() #10 /storage/home/www/magento-test/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(424): Magento\Framework\Model\ResourceModel\Db\VersionControl\AbstractDb->processAfterSaves() #11 /storage/home/www/magento-test/vendor/magento/module-sales/Model/ResourceModel/Order.php(180): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save() #12 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\ResourceModel\Order->save() #13 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\ResourceModel\Order\Interceptor->___callParent() #14 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\ResourceModel\Order\Interceptor->Magento\Framework\Interception\{closure}() #15 /storage/home/www/magento-test/generated/code/Magento/Sales/Model/ResourceModel/Order/Interceptor.php(32): Magento\Sales\Model\ResourceModel\Order\Interceptor->___callPlugins() #16 /storage/home/www/magento-test/vendor/magento/module-sales/Model/OrderRepository.php(276): Magento\Sales\Model\ResourceModel\Order\Interceptor->save() #17 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\OrderRepository->save() #18 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\OrderRepository\Interceptor->___callParent() #19 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}() #20 /storage/home/www/magento-test/generated/code/Magento/Sales/Model/OrderRepository/Interceptor.php(59): Magento\Sales\Model\OrderRepository\Interceptor->___callPlugins() #21 /storage/home/www/magento-test/vendor/magento/module-sales/Model/Service/OrderService.php(216): Magento\Sales\Model\OrderRepository\Interceptor->save() #22 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place() #23 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent() #24 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}() #25 /storage/home/www/magento-test/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(32): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins() #26 /storage/home/www/magento-test/vendor/magento/module-quote/Model/QuoteManagement.php(566): Magento\Sales\Model\Service\OrderService\Interceptor->place() #27 /storage/home/www/magento-test/vendor/magento/module-quote/Model/QuoteManagement.php(456): Magento\Quote\Model\QuoteManagement->submitQuote() #28 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit() #29 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent() #30 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}() #31 /storage/home/www/magento-test/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(23): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins() #32 /storage/home/www/magento-test/vendor/magento/module-sales/Model/AdminOrder/Create.php(1978): Magento\Quote\Model\QuoteManagement\Interceptor->submit() #33 /storage/home/www/magento-test/vendor/magento/module-sales/Controller/Adminhtml/Order/Create/Save.php(52): Magento\Sales\Model\AdminOrder\Create->createOrder() #34 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Create\Save->execute() #35 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callParent() #36 /storage/home/www/magento-test/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->Magento\Framework\Interception\{closure}() #37 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() #38 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->Magento\Framework\Interception\{closure}() #39 /storage/home/www/magento-test/generated/code/Magento/Sales/Controller/Adminhtml/Order/Create/Save/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callPlugins() #40 /storage/home/www/magento-test/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->execute() #41 /storage/home/www/magento-test/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch() #42 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch() #43 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callParent() #44 /storage/home/www/magento-test/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->Magento\Framework\Interception\{closure}() #45 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() #46 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->Magento\Framework\Interception\{closure}() #47 /storage/home/www/magento-test/generated/code/Magento/Sales/Controller/Adminhtml/Order/Create/Save/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->___callPlugins() #48 /storage/home/www/magento-test/vendor/magento/framework/App/FrontController.php(186): Magento\Sales\Controller\Adminhtml\Order\Create\Save\Interceptor->dispatch() #49 /storage/home/www/magento-test/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest() #50 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch() #51 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent() #52 /storage/home/www/magento-test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() #53 /storage/home/www/magento-test/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins() #54 /storage/home/www/magento-test/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch() #55 /storage/home/www/magento-test/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch() #56 /storage/home/www/magento-test/pub/index.php(29): Magento\Framework\App\Bootstrap->run() #57 {main}`
> 
> Order details:
> 
> * customer NOT LOGGED IN
> * Shipping address provided
> * Billing address same as billingt
> 
> Please let me know if you need more data.

**Comment by Eyekandy** [comment]
I believe it to be ok now

**Comment by rkarkut** [comment]
We have fixed it in version 20.5.8 (magento-module version 1.2.8)
