### ISSUE TITLE
Problem in M2.4.6-p3

### ISSUE THREAD

**Issue by DanielJakubowiczStrix** [GetResponse/magento#61]
https://github.com/GetResponse/magento/blob/de7773d9826f07949352369532c056617e174869/view/frontend/templates/getresponse_tracking_code.phtml#L44

Problem in M2.4.6-p3

![image](https://github.com/GetResponse/magento/assets/92792807/b20380ce-c9f5-402c-9592-f02b9e6bdd1c)

Should remain

`$(document).ready(function() {`

**Comment by MTheProgrammer** [comment]
It would be nice to have a configuration to enable/disable certain tracking options. There are merchants who are fine with tracking handled by Magento Observers as additional JS impacts page speed.

**Comment by rkarkut** [comment]
Hello there, we have fixed reported issue.
It's possible to disconnect WebConnect during configuration in GetResponse (there is additional switch for WebConnect).
